name: flutter_pangle_ads
description: 【持续更新】一款优质的穿山甲 Flutter 广告变现插件，支持 Android、iOS 平台，可快速接入进行广告变现。
version: 3.1.1
homepage: https://flutterads.top
repository: https://github.com/FlutterAds/flutter_pangle_ads
issue_tracker: https://github.com/FlutterAds/flutter_pangle_ads/issues
documentation: https://github.com/FlutterAds/flutter_pangle_ads/wiki
topics: [flutterads, ads, pangle, bytedance, income]
funding: [https://github.com/FlutterAds/.github]

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.zero.flutter_pangle_ads
        pluginClass: FlutterPangleAdsPlugin
      ios:
        pluginClass: FlutterPangleAdsPlugin
